version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: store
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: store
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: